identifier:
  image: semtech/mu-identifier:1.2.0
  links:
    - dispatcher:dispatcher
  ports:
    - "80:80"
dispatcher:
  image: semtech/mu-dispatcher:1.1.0
  links:
    - books:books
  volumes:
    - ./backend/dispatcher:/config
books:
  image: madnificent/books-service:1.0.0
  links:
    - db:database
migrations:
  image: semtech/mu-migrations-service:0.2.0
  links:
    - db:database
  volumes:
    - ./backend/migrations:/data/migrations
db:
  image: tenforce/virtuoso:1.1.0-virtuoso7.2.0
  environment:
    SPARQL_UPDATE: "true"
  ports:
    - "8890:8890"
